# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


  
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzurePipeline'
    subscriptionId: '330413c2-a12a-4498-9f3c-e9109ad4210c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myResourceGroup'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreatWebApp/azureDeploy.json'
    overrideParameters: '-projectName mypr02 -linkedTemplateUri https://raw.githubusercontent.com/Megha-code/Test2020-repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'